# Generated by Django 5.1.5 on 2025-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuadroCargos',
            fields=[
                ('codigo_controle', models.AutoField(primary_key=True, serialize=False)),
                ('nome_quadro', models.CharField(max_length=255)),
                ('data_inclusao', models.DateField()),
                ('data_atualizacao', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('revogado', models.BooleanField(default=False)),
            ],
        ),
    ]
