# Generated by Django 5.1.5 on 2025-02-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orgao',
            new_name='Orgaos',
        ),
        migrations.RenameModel(
            old_name='QuadroCargos',
            new_name='QuadroDeCargos',
        ),
    ]
