# Generated by Django 5.1.5 on 2025-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quadrocargos',
            options={'ordering': ['data_inclusao'], 'verbose_name': 'Quadro de Cargo', 'verbose_name_plural': 'Quadros de Cargos'},
        ),
        migrations.AlterField(
            model_name='quadrocargos',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='quadrocargos',
            name='data_inclusao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Inclusão'),
        ),
        migrations.AlterField(
            model_name='quadrocargos',
            name='nome_quadro',
            field=models.CharField(max_length=255, verbose_name='Nome do Quadro'),
        ),
        migrations.AlterField(
            model_name='quadrocargos',
            name='revogado',
            field=models.BooleanField(default=False, verbose_name='Revogado'),
        ),
        migrations.AlterField(
            model_name='quadrocargos',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente')], default='ativo', max_length=50, verbose_name='Status'),
        ),
    ]
