# Generated by Django 5.1.5 on 2025-01-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_quadrocargos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_cargo_vigente', models.CharField(max_length=255)),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
                ('vagas_autorizadas', models.IntegerField()),
                ('vagas_ocupadas', models.IntegerField()),
                ('cargo_acumulavel', models.BooleanField(default=False)),
                ('dedicacao_exclusiva', models.BooleanField(default=False)),
                ('cbo', models.CharField(max_length=10)),
                ('lei_criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atolegal')),
                ('escolaridade_minima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escolaridade')),
                ('ordem_profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ordemprofissional')),
                ('tipo_provimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoprovimento')),
            ],
        ),
    ]
