# Generated by Django 5.1.5 on 2025-02-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_orgao_orgaos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orgaos',
            new_name='Orgao',
        ),
        migrations.RenameModel(
            old_name='QuadroDeCargos',
            new_name='QuadroCargos',
        ),
        migrations.AlterField(
            model_name='cargos',
            name='quadro_cargos',
            field=models.IntegerField(default=0),
        ),
    ]
