# Generated by Django 5.1.5 on 2025-02-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_quadrocargos_options_alter_quadrocargos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='lei_criacao',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='escolaridade_minima',
        ),
        migrations.AlterField(
            model_name='orgao',
            name='municipio',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='ordem_profissional',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='tipo_provimento',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='nome_do_cargo_vigente',
            new_name='nome_do_cargo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='cargo_acumulavel',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='data_fim_vigencia',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='data_inicio_vigencia',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='dedicacao_exclusiva',
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='lei_criacao',
        ),
        migrations.RemoveField(
            model_name='quadrocargos',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='quadrocargos',
            name='data_inclusao',
        ),
        migrations.RemoveField(
            model_name='quadrocargos',
            name='revogado',
        ),
        migrations.RemoveField(
            model_name='quadrocargos',
            name='status',
        ),
        migrations.AddField(
            model_name='cargo',
            name='quadro_cargos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgao',
            name='codigo_ibge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quadrocargos',
            name='nome_quadro',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AtoLegal',
        ),
        migrations.DeleteModel(
            name='Escolaridade',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='OrdemProfissional',
        ),
        migrations.DeleteModel(
            name='TipoProvimento',
        ),
    ]
