# Generated by Django 5.1.5 on 2025-02-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cargo_lei_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='quadro_cargos',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='vagas_autorizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='vagas_ocupadas',
            field=models.IntegerField(default=0),
        ),
    ]
